CREATE TABLE USERS(
    USER_ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE WALLETS(
    WALLET_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    USER_ID INT REFERENCES USERS(USER_ID)
);