import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProtectedRoute from "@/components/ProtectedRoute";
import CryptoProvider from "@/context/coins/CryptoProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={inter.className}
				style={{ height: "100vh", width: "100vw" }}
			>
				<ProtectedRoute>
					<CryptoProvider>{children}</CryptoProvider>
				</ProtectedRoute>
				<ToastContainer />
			</body>
		</html>
	);
}
